<a href="https://colab.research.google.com/github/ZXEcoder/machine_learning_fundas/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()


7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[2,6,7],[6,7,8]],[[1,2,3],[4,5,6],[2,6,7],[6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 6, 7],
         [6, 7, 8]],

        [[1, 2, 3],
         [4, 5, 6],
         [2, 6, 7],
         [6, 7, 8]]])

In [11]:
TENSOR.ndim


3

In [12]:
TENSOR.shape


torch.Size([2, 4, 3])

In [13]:
TENSOR[1,1,0]

tensor(4)

###random tensor

why random tensor?

Random tensors are important beecause the way many neural networks learn is that
they start with tensors full  of random numbers and then adjust random numbers 
to better represent the data,
`start with random numbers -> look at data -> update random numbers -> look at data -> uodate random number`


In [14]:
# create random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1944, 0.8145, 0.1322, 0.5683],
        [0.6800, 0.2307, 0.8722, 0.9124],
        [0.2765, 0.0104, 0.5159, 0.9290]])

In [15]:
random_tensor.ndim


2

In [16]:
random_image_size_tensor = torch.rand(size=(224,224,3))# height, width,color rgb
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [17]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

###Creating range of tensors

In [20]:
one_to_ten = torch.arange(start=1, end=11 ,step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype


torch.float32

In [24]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor+int_32_tensor

tensor([ 6., 12., 18.])

In [28]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9711, 0.6999, 0.1315, 0.1064],
        [0.1066, 0.0752, 0.8555, 0.5524],
        [0.8491, 0.3482, 0.6480, 0.7201]])

In [29]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device that tensor is on:{some_tensor.device}")


tensor([[0.9711, 0.6999, 0.1315, 0.1064],
        [0.1066, 0.0752, 0.8555, 0.5524],
        [0.8491, 0.3482, 0.6480, 0.7201]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device that tensor is on:cpu


In [30]:
some_tensor.type(torch.float16)

tensor([[0.9712, 0.6997, 0.1315, 0.1064],
        [0.1066, 0.0752, 0.8555, 0.5522],
        [0.8491, 0.3481, 0.6479, 0.7202]], dtype=torch.float16)

###manipulating tensor

In [31]:
# creating some tensor
tensor = torch.tensor([1,4,5])
tensor+10

tensor([11, 14, 15])

In [32]:
tensor-10

tensor([-9, -6, -5])

In [33]:
tensor/10

tensor([0.1000, 0.4000, 0.5000])

###matrix multiplication

In [34]:
torch.matmul(tensor,tensor)

tensor(42)

In [35]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)  

tensor(42)
CPU times: user 1.97 ms, sys: 0 ns, total: 1.97 ms
Wall time: 3.01 ms


### one of the most common errors in the deep learning for matix multiplication
  * shape errors
  * (m*n) * (n*m)

In [36]:
torch.matmul(torch.rand(10,9),torch.rand(9,10)).shape


torch.Size([10, 10])

In [37]:
ju=torch.matmul(torch.rand(5,5),torch.rand(5,3))
print(ju)


tensor([[1.3020, 1.4135, 0.8903],
        [1.1472, 1.3749, 0.6500],
        [1.9402, 1.8240, 1.2145],
        [2.2055, 1.6606, 1.1951],
        [2.2391, 1.8423, 1.1634]])


In [38]:
# to fix our tensor shape issue we can use transpose
tensor_A=torch.rand(3,2)
tensor_B=torch.rand(3,2)
tensor_A

tensor([[0.5263, 0.2440],
        [0.9887, 0.9804],
        [0.8297, 0.0403]])

In [39]:
tensor_A.T


tensor([[0.5263, 0.9887, 0.8297],
        [0.2440, 0.9804, 0.0403]])

In [40]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above ), tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- innner dimension must match")
print("output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above ), tensor_B.T=torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- innner dimension must match
output:

tensor([[0.3225, 0.4883, 0.3993],
        [1.0195, 1.2874, 1.2565],
        [0.2358, 0.5258, 0.2955]])

output shape: torch.Size([3, 3])


###Finding the min max mean sum etc(tensor aggregation)

In [41]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [42]:
# find the min
torch.min(x),x.min()


(tensor(0), tensor(0))

In [43]:
torch.max(x),x.max()


(tensor(90), tensor(90))

In [44]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [45]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [46]:
x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [47]:
x.argmax(),torch.argmax(x)

(tensor(9), tensor(9))

##reshaping stacking aqueezing and unsqueeing tensors

In [48]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
x_reshape =x.reshape(1,9)
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
z =x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
#view function is likw a reshape function but it can change he original
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [52]:
# stackin tensors
x_staked = torch.stack([x,x,x,x],dim=1)
x_staked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [53]:
#torch.squeeze()
x_reshape,x_reshape.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_reshape.squeeze(),x_reshape.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
#torch.unsqueze
x_reshape.unsqueeze(dim=0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [56]:
#toch.permute
x_original = torch.rand(size=(224,224,3))
x_permute = x_original.permute(2,0,1)
print(f"preivious shape{x_original.shape}")
print(f"new shape: {x_permute.shape}")

preivious shapetorch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [57]:
x_original[0,0,0]=5

In [58]:
x_permute

tensor([[[5.0000, 0.9857, 0.4472,  ..., 0.5634, 0.3536, 0.5204],
         [0.1702, 0.9885, 0.9738,  ..., 0.4285, 0.1550, 0.1427],
         [0.0669, 0.6407, 0.8554,  ..., 0.2426, 0.5035, 0.8412],
         ...,
         [0.2537, 0.8831, 0.5363,  ..., 0.9694, 0.2579, 0.9247],
         [0.0091, 0.2880, 0.8581,  ..., 0.7708, 0.3507, 0.9163],
         [0.6462, 0.5258, 0.1994,  ..., 0.2203, 0.8008, 0.0784]],

        [[0.8461, 0.3804, 0.6921,  ..., 0.8383, 0.3022, 0.7762],
         [0.7188, 0.8250, 0.5258,  ..., 0.1862, 0.8565, 0.5260],
         [0.3658, 0.6249, 0.1917,  ..., 0.8799, 0.6508, 0.3777],
         ...,
         [0.5535, 0.4410, 0.3258,  ..., 0.9825, 0.8651, 0.4441],
         [0.0347, 0.5659, 0.7048,  ..., 0.2260, 0.9717, 0.3982],
         [0.4895, 0.2771, 0.7446,  ..., 0.8804, 0.2808, 0.2291]],

        [[0.8419, 0.9279, 0.9551,  ..., 0.5396, 0.8940, 0.0355],
         [0.5403, 0.6135, 0.5559,  ..., 0.6313, 0.5463, 0.8311],
         [0.1462, 0.1063, 0.0267,  ..., 0.2439, 0.5508, 0.

###Indexing (selecting data from tensors)
same as numbpy

In [59]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0][0][0]

tensor(1)

In [61]:
x[0,0,0]

tensor(1)

In [62]:
x[0,1,0]

tensor(4)

In [63]:
# you can also use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [64]:
#get all values of 0th and 1st dimensisons but only  index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [65]:
x[:,:,1]

tensor([[2, 5, 8]])

## pytorch tensor and numpy

In [66]:
import torch 
import numpy  as np

array = np.arange(1.0,8.0)
tensor =  torch.from_numpy(array)# warning: pytorch default float 32 and numpy float64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [69]:
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

PYTORCH REPRODUCIBILITY

In [70]:
torch.rand(3,3)

tensor([[0.2055, 0.0974, 0.6107],
        [0.8216, 0.3184, 0.8653],
        [0.7903, 0.8877, 0.7890]])

In [71]:
r_a=torch.rand(3,4)
r_b=torch.rand(3,4)
r_a,r_b
print(r_a==r_b)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
import torch
# lets make  some random number reproducible
#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED )
random_tensor_c =torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running tensors and pytorch objects on the gpus(and making faster computation)

In [74]:
!nvidia-smi

Thu Jun  8 12:52:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [75]:
# check for GPU access with pytorch
import torch
torch.cuda.is_available()


True

In [76]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
torch.cuda.device_count()

1

## putting tensors (and models) on the gpu

In [79]:
# create a tensor (default on the cpu)
tensor= torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [80]:
tensor_on_gpu =tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##moving tensor back to cpu

In [82]:
#To fix the gpu twnsor with numoy issue we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])